account/urls.py
from django.urls import path
from .views import user_logout, signup, user_login

app_name = 'account'

urlpatterns = [
    path('logout/', user_logout, name='user_logout'),
    path('signup/', signup, name='user_register'),
    path('login/', user_login, name='user_login'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('account/', include('account.urls')),
]

todo/urls.py
from django.urls import path
from .views import index, delete_todo_category, delete_todo, edit_todo, create_todo, category_index, \
    create_todo_category

app_name = 'todo'

urlpatterns = [
    path('', index, name='homepage'),
    path('delete/<int:todo_id>', delete_todo, name='delete_todo'),
    path('delete_category/<int:cat_id>', delete_todo_category, name='delete_todo_category'),
    path('edit/<int:todo_id>', edit_todo, name='edit_todo'),
    path('create/', create_todo, name='create_todo'),
    path('create_category/', create_todo_category, name='create_todo_category'),
    path('category_index/', category_index, name='category_index'),
]

account/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.contrib.auth.models import User
from django.db import models


class TodoCategory(models.Model):
    category = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.category


class TodoList(models.Model):
    title = models.CharField(max_length=30)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField()
    category = models.ForeignKey(TodoCategory, on_delete=models.CASCADE)
    is_completed = models.BooleanField(default=False)
    due_date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from .models import TodoList, TodoCategory


class TodoCreateForm(forms.ModelForm):
    class Meta:
        model = TodoList
        exclude = ['owner']


class TodoCreateCategoryForm(forms.ModelForm):
    class Meta:
        model = TodoCategory
        fields = '__all__'

account/views.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import redirect


app_name = 'account'


def signup(request):
    template_name = 'account/register.html'
    if request.method == 'POST':
        signup_form = UserCreationForm(request.POST)
        if signup_form.is_valid():
            signup_form.save()
            username = signup_form.cleaned_data.get('username')
            raw_password = signup_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('todo:homepage')
    else:
        signup_form = UserCreationForm()
        context = {
            'signup_form': signup_form
        }
        return render(request, template_name=template_name, context=context)


def user_login(request):
    template_name = 'account/login.html'
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todo:homepage')
        else:
            return redirect('account:user_register')
    else:
        login_form = AuthenticationForm(request.POST)
        context = {
            'login_form': login_form
            }
    return render(request, template_name=template_name, context=context)


def user_logout(request):
    logout(request)
    return redirect('todo:homepage')

todo/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import TodoList, TodoCategory
from .forms import TodoCreateForm, TodoCreateCategoryForm


@login_required
def index(request):
    template_name = 'todo/index.html'
    #todos = TodoList.objects.all()
    todos = TodoList.objects.filter(owner=request.user)
    context = {
        'todos': todos,
    }
    return render(request, template_name=template_name, context=context)


@login_required
def create_todo(request):
    template_name = 'todo/create.html'
    todo_form = TodoCreateForm()
    if request.method == 'POST':
        todo_form = TodoCreateForm(request.POST)
        if todo_form.is_valid():
            todo_item = todo_form.save(commit=False)
            todo_item.owner = request.user
            todo_item.save()
            return redirect('todo:homepage')
    context = {
        'todo_form': todo_form,
    }
    return render(request, template_name=template_name, context=context)


@login_required
def edit_todo(request, todo_id):
    template_name = 'todo/edit.html'
    todo = TodoList.objects.get(id=todo_id)

    todo_form = TodoCreateForm(instance=todo)

    if request.method == 'POST':
        todo_form = TodoCreateForm(request.POST, instance=todo)
        if todo_form.is_valid():
            todo_form.save()
            return redirect('todo:homepage')
    context = {
        'todo': todo,
        'todo_form': todo_form
    }
    return render(request, template_name=template_name, context=context)


@login_required
def delete_todo(request, todo_id):
    template_name = 'todo/delete.html'
    todo = TodoList.objects.get(id=todo_id)

    if request.method == 'POST':
        todo.delete()
        return redirect('todo:homepage')
    context = {

    }
    return render(request, template_name=template_name, context=context)


@login_required
def create_todo_category(request):
    template_name = 'todo/create_category.html'
    todo_category_form = TodoCreateCategoryForm()
    if request.method == 'POST':
        todo_category_form = TodoCreateCategoryForm(request.POST)
        if todo_category_form.is_valid():
            todo_category_item = todo_category_form.save()
            return redirect('todo:category_index')
    context = {
        'todo_category_form': todo_category_form,
    }
    return render(request, template_name=template_name, context=context)


@login_required
def category_index(request):
    template_name = 'todo/category_index.html'
    categories = TodoCategory.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, template_name=template_name, context=context)


@login_required
def delete_todo_category(request, cat_id):
    template_name = 'todo/delete_category.html'
    category = TodoCategory.objects.get(id=cat_id)
    if request.method == 'POST':
        category.delete()
        return redirect('todo:category_index')
    context = {

    }
    return render(request, template_name=template_name, context=context)

templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>{% block page_title %} {% endblock page_title %}</title>
    <style>
        body{
            background-color: #638CB8;
            }
        .center-column{
        width:600px;
        margin:20px auto;
        padding:20px;
        background-color: #FFF;
        border-radius: 3px;
        box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75)
        }

        .item-row{
        background-color: #906abd;
        margin:10px;
        padding:20px;
        border-radius:3px;
        color:#fff;
        font-size:16px;
        box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75)
        }

    </style>
</head>
<body>
{% block navbar %} {% endblock navbar %}
{% block todos %} {% endblock todos %}
</body>
</html>

templates/todo/category_index.html
{% extends 'todo/base.html' %}

{% block page_title %}
  Todo List
{% endblock page_title %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'todo:homepage' %}">Todo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'todo:homepage' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todo:category_index' %}">Todo Categories</a>
            </li>
             {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="">Profile</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_logout' %}">Logout</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link" href="">Welcome - {{request.user}}</a>
              </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_login' %}">Login</a>
                </li>

                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_register' %}">Register</a>
                </li>

            {% endif %}



          </ul>
        </div>
      </div>
    </nav>
{% endblock navbar %}


    {% block todos %}
        <div class="center-column">
            <h1 style="display:inline;">Todo Categories</h1> <a href="{% url 'todo:create_todo_category' %}" class="btn btn-primary " style="display:inline; position:relative; left: 120px;">Add Category</a>
                {% for category in categories %}
                <div class="item-row">
                    <a href="" class="btn btn-sm btn-info">Edit</a>
                    <a href="{% url 'todo:delete_todo_category' category.id  %}" class="btn btn-sm btn-danger">Delete</a>
                        {{category}}
                </div>
                {% endfor %}
    {% endblock todos %}
</div>

templates/todo/create.html
{% extends 'todo/base.html' %}
{% load crispy_forms_tags %}
{% block page_title %}
  Todo List
{% endblock page_title %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'todo:homepage' %}">Todo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'todo:homepage' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todo:category_index' %}">Todo Categories</a>
            </li>
             {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_logout' %}">Logout</a>
              </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_login' %}">Login</a>
                </li>

                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_register' %}">Register</a>
                </li>
            {% endif %}



          </ul>
        </div>
      </div>
    </nav>
{% endblock navbar %}


    {% block todos %}
        <div class="center-column">
            <h1>Create New</h1>
                <div class="item-row">

                    <form action="" method="post">
                        {% csrf_token %}
                        {{todo_form | crispy}}
                        <input name ="create_todo" class="btn btn-primary" type="submit" value="Submit">
                    </form>
                </div>
    {% endblock todos %}
</div>

templates/todo/create_category.html
{% extends 'todo/base.html' %}
{% load crispy_forms_tags %}
{% block page_title %}
  Todo List
{% endblock page_title %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'todo:homepage' %}">Todo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'todo:homepage' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todo:category_index' %}">Todo Categories</a>
            </li>
             {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_logout' %}">Logout</a>
              </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_login' %}">Login</a>
                </li>

                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_register' %}">Register</a>
                </li>
            {% endif %}



          </ul>
        </div>
      </div>
    </nav>
{% endblock navbar %}


    {% block todos %}
        <div class="center-column">
            <h1>Create New Category</h1>
                <div class="item-row">

                    <form action="" method="post">
                        {% csrf_token %}
                        {{todo_category_form | crispy}}
                        <input name ="create_todo" class="btn btn-primary" type="submit" value="Submit">
                    </form>
                </div>
    {% endblock todos %}
</div>

templates/todo/delete.html
{% extends 'todo/base.html' %}

{% block page_title %}
  Todo List
{% endblock page_title %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Todo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todo:category_index' %}">Todo Categories</a>
            </li>
             {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_logout' %}">Logout</a>
              </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="#">Login</a>
                </li>

                 <li class="nav-item">
                  <a class="nav-link" href="#">Register</a>
                </li>
            {% endif %}



          </ul>
        </div>
      </div>
    </nav>
{% endblock navbar %}


    {% block todos %}
        <div class="center-column">
            <h1>Todo List</h1>
                <div class="item-row">
                    <p>Are you sure you want to delete this Todo Item?</p>
                    <p> <a href="{% url 'todo:homepage' %}">Cancel</a>  </p>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input name ="delete_todo" class="btn btn-danger" type="submit" value="Confirm Delete">
                    </form>
                </div>
    {% endblock todos %}
</div>

templates/todo/delete_category.html
{% extends 'todo/base.html' %}

{% block page_title %}
  Todo List
{% endblock page_title %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Todo Category</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todo:category_index' %}">Todo Categories</a>
            </li>
             {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_logout' %}">Logout</a>
              </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="#">Login</a>
                </li>

                 <li class="nav-item">
                  <a class="nav-link" href="#">Register</a>
                </li>
            {% endif %}



          </ul>
        </div>
      </div>
    </nav>
{% endblock navbar %}


    {% block todos %}
        <div class="center-column">
            <h1>Todo Category</h1>
                <div class="item-row">
                    <p>Are you sure you want to delete this Todo Category?</p>
                    <p> <a href="{% url 'todo:category_index' %}">Cancel</a>  </p>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input name ="delete_todo" class="btn btn-danger" type="submit" value="Confirm Delete">
                    </form>
                </div>
    {% endblock todos %}
</div>

templates/todo/edit.html
{% extends 'todo/base.html' %}
{% load crispy_forms_tags %}
{% block page_title %}
  Todo List
{% endblock page_title %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'todo:homepage' %}">Todo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'todo:homepage' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Todo Categories</a>
            </li>
             {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_logout' %}">Logout</a>
              </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="#">Login</a>
                </li>

                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'todo:user_register' %}">Register</a>
                </li>
            {% endif %}



          </ul>
        </div>
      </div>
    </nav>
{% endblock navbar %}


    {% block todos %}
        <div class="center-column">
            <h1>Todo List</h1>
                <div class="item-row">
                    <p>Edit and Update Todo Item</p>
                    <p> <a href="{% url 'todo:homepage' %}">Cancel</a>  </p>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{todo_form | crispy}}
                        <input name ="update_todo" class="btn btn-primary" type="submit" value="Update">
                    </form>
                </div>
    {% endblock todos %}
</div>

templates/todo/index.html
{% extends 'todo/base.html' %}

{% block page_title %}
  Todo List
{% endblock page_title %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Todo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Todo Categories</a>
            </li>
             {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account:user_logout' %}">Logout</a>
              </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="#">Login</a>
                </li>

                 <li class="nav-item">
                  <a class="nav-link" href="#">Register</a>
                </li>
            {% endif %}



          </ul>
        </div>
      </div>
    </nav>
{% endblock navbar %}


    {% block todos %}
        <div class="center-column">
            <h1>Todo List</h1>
                {% for todo in todos %}
                <div class="item-row">
                    <a href="{% url 'todo:edit_todo' todo.id %}" class="btn btn-sm btn-info">Edit</a>
                    <a href="{% url 'todo:delete_todo' todo.id %}" class="btn btn-sm btn-danger">Delete</a>
                    {% if todo.is_completed %}
                        <strike>{{todo}}</strike>
                    {% else %}
                        {{todo}}
                    {% endif %}
                </div>
                {% endfor %}
    {% endblock todos %}
</div>